---
- hosts: localhost

  vars_files:
    - ../vars/credentials.yml
    - ../vars/server.yml

  tasks:
    - name: Check for API key 
      assert:
        that: "credentials.digital_ocean.api_key is defined"
        msg: Please ensure `credentials.digital_ocean.api_key` is defined in `host_vars/localhost/credentials`

    - name: Ensure public key exists on DigitalOcean
      community.digitalocean.digital_ocean_sshkey:
        oauth_token: "{{ credentials.digital_ocean.api_key }}"
        name: "{{ server.ssh_key_name }}"
        ssh_pub_key: "{{ lookup('file', '../keys/ansible.pub') }}"
      register: public_key_create

    - name: Provision a new Ubuntu DigitalOcean Server
      community.digitalocean.digital_ocean_droplet:
        state: present
        oauth_token: "{{ credentials.digital_ocean.api_key }}"
        image: "{{ server.image }}"
        region: "{{ server.region }}"
        size: "{{ server.size }}"
        ssh_keys:
          - "{{ public_key_create.data.ssh_key.id }}"
        name: "{{ server.name }}"
        unique_name: yes
        wait: yes
      register: server_create

    - name: Create a new volume
      community.digitalocean.digital_ocean_block_storage:
        oauth_token: "{{ credentials.digital_ocean.api_key }}"
        block_size: "{{ volume.block_size }}"
        command: create
        region: "{{ server.region }}"
        state: present
        volume_name: "{{ volume.name }}"

    - name: Attach volume to created server
      community.digitalocean.digital_ocean_block_storage:
        oauth_token: "{{ credentials.digital_ocean.api_key }}"
        region: "{{ server.region }}"
        command: attach
        state: present
        volume_name: "{{ volume.name }}"
        droplet_id: "{{ server_create.data.droplet.id }}"

    - name: Extract droplet public IPv4 address
      set_fact:
        droplet_ip: "{{ (server_create.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public') | first).ip_address }}"

    - name: Add new server to static inventory file
      template:
        src: ../templates/inventory.j2
        dest: ../inventory

    - name: Add new server to in-memory inventory
      add_host:
        name: minecraft
        ansible_ssh_host: "{{ droplet_ip }}"
      changed_when: False

    - name: Register hostname with DNSimple
      community.general.dnsimple:
        account_email: "{{ credentials.dnsimple.account_email }}"
        account_api_token: "{{ credentials.dnsimple.account_api_token }}"
        domain: "{{ dns.domain }}"
        record: "{{ dns.hostname | default(server.name) }}"
        type: A
        ttl: "{{ dns.ttl | default(300) }}"
        solo: yes
        value: "{{ droplet_ip }}"
        state: present
      when:
        - dns is defined
        - credentials is defined
        - credentials.dnsimple is defined
        - credentials.dnsimple.account_email is defined
        - credentials.dnsimple.account_api_token is defined

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ droplet_ip }}"
        port: 22 
        delay: 30
        timeout: 320
        state: started

- hosts: minecraft
  user: root

  vars_files:
    - ../vars/server.yml

  vars:
    device_path: "/dev/disk/by-id/scsi-0DO_Volume_{{ volume.name }}"

  pre_tasks:
    - name: Partition block storage device
      community.general.parted:
        align: optimal
        device: "{{ device_path }}"
        part_start: "0%"
        part_end: "100%"
        part_type: primary

    - name: Make filesystem on device
      community.general.filesystem:
        fstype: ext4
        dev: "{{ device_path }}"

    - name: Mount block storage on Minecraft data directory
      ansible.posix.mount:
        path: "{{ minecraft_home | dirname }}"
        src: "{{ device_path }}"
        state: mounted
        fstype: ext4

  roles:
    - devops-coop.minecraft
